### ISSUE TITLE
B1.2.F2U1:  As a map manager, I want to publish services to the map, so anyone can see them

### ISSUE THREAD

**Issue by MatiasNurmi** [ecosystemos/ecosystem-mapping#1]
**Figma Prototype URL**: As an ecosystem map manager I want to publish services to the map so anyone can see them([User Story Link](https://www.figma.com/file/mrO0mA0aw4aSgVIq3Iqkq0/B1.2.-Ecosystem-Mapping?node-id=2880%3A15309))
**Figma Designer View**: User Story ([Figma Link](https://www.figma.com/file/mrO0mA0aw4aSgVIq3Iqkq0/B1.2.-Ecosystem-Mapping?node-id=2880%3A22925))
**Loom walktrough URL**: Ecosystem Mapping ([Link](https://www.youtube.com/watch?v=rcsCFau0NfQ))

*Includes:* 
**Relevant user story Google Doc**: ([User Story Link](https://docs.google.com/document/d/17yGFkY-gnbv_TRdi36RAJGqlTLeMTWSkbshLa8bvG18/edit#))

**Completion Status**
- [x] UX Logic
- [ ] Design System Components 
- [ ] Visual Design
- [ ] Text Copy
- [ ] Data Model
- [ ] Back-end functions documentation
- [ ] User Story Documentation finalised
- [ ] Milestone Version updates

**Comment by darshan-ht** [comment]
Vercel Link .

https://startup-commons.vercel.app/

**Comment by abhijeets-ht** [comment]
@valto 

vercel Link-
https://startup-commons.vercel.app

**Comment by alhasanmhdali** [comment]
@abhijeets-ht I have added some comments regarding this user story
- [ ] For the timezone field I suggest this to be a dropdown list as in the link as this will be easier for users
https://i.stack.imgur.com/6p0bb.png
- [ ] For Location options I think it is better to list these two options (Online, Venue) vertically, and when checking any of the options a text box appears next to it to mention the link or the location
![image](https://user-images.githubusercontent.com/65980846/121077906-e5fb8580-c7e0-11eb-8f3a-055dde1347cc.png)
- [ ] For each section of adding service from, I think it is better to add a "Continue" or "Next" button here that will collapse this section and expand the next section so that the user will keep focusing on what he is filling now
- [ ] In the **Service Information** section, for the first two questions user's options should be limited to the available services only, so this may be a dropdown list
- [ ] "**Is this a verified service**" should be a radio option instead of checkboxes
- [ ] "**Which phase is this service for**" is missing
- [ ] **Publish** button should be unavailable until the user fill in all required information
- [ ] There is no filter button inside the adding service form, you should move it to the map page
- [ ] For **Tags** input, Can we user this logic here? https://www.jqueryscript.net/demo/Tagging-System-Autocomplete-Amsify-Suggestags/
- [ ] In the popup when saving the service, we need to add buttons to continue editing or back to map page
- [ ] In the popup when publishing the service, we need a button to return to the map and view the service there

**Comment by abhijeets-ht** [comment]
@alhasanmhdali Thanks for feedback , will take a look into it and send you updated vercel link

**Comment by abhijeets-ht** [comment]
Hi @alhasanmhdali 
The accordion in chakra ui , is not that much programmable , it allow only to use the , defined props , so can we use accordion from any other , librarary except chakra ui ?

**Comment by valto** [comment]
@abhijeets-ht regards to chakra accordion, what modification is not possible in it that you are trying to do?

**Comment by abhijeets-ht** [comment]
@valto as per feedback, I tried For each section of adding service from, to add a "Continue" or "Next" button here that will collapse this section and expand the next section so that the user will keep focusing on what he is filling now

**Comment by abhijeets-ht** [comment]
Hi @alhasanmhdali 

We have accomplished all the above feedback and changes you shared 
Here is the vercel link for ecosystem mapping 
https://startup-commons-akljwlcjj-abhijeetsht.vercel.app/home

For this point "n the popup when publishing the service, we need a button to return to the map and view the service there", when we get the data from API , we need to handle this at time of integration because as of now we not have real data

**Comment by alhasanmhdali** [comment]
Hi @abhijeets-ht 

We have some updates to apply to the design, I will list them below:

- [ ] Let's use the design layout in the "Prototype" page in [Fimga](https://www.figma.com/file/mrO0mA0aw4aSgVIq3Iqkq0/B1.2.-Ecosystem-Mapping?node-id=2880%3A46101) file, there are a few differences
![image](https://user-images.githubusercontent.com/65980846/122647678-153dbb00-d12e-11eb-986b-c4b15540a07f.png)

- [x] Update location selection to have (Region, Countries, Cities) from a pre-defined list when creating a new map
![image](https://user-images.githubusercontent.com/65980846/122647738-5f26a100-d12e-11eb-984f-bd6a9c32b0f0.png)
![image](https://user-images.githubusercontent.com/65980846/122647746-63eb5500-d12e-11eb-9cb1-dceb899b1b53.png)

- [x] Rename "Service name / Organisation" to "Service Owner/Organisation"
- [x] Rename "Service type" to "Service Primary Focus" and make all choices as a radio button, so user can select only ONE option
![image](https://user-images.githubusercontent.com/65980846/122647906-436fca80-d12f-11eb-9b0d-042eb0d3fb66.png)

- [ ] Remove "Application" section after service type
- [x] In service location, change "Online" and "Venue" options as checkboxes as the user can select both options together
![image](https://user-images.githubusercontent.com/65980846/122647897-3521ae80-d12f-11eb-980b-cba79922f576.png)

- [x] In the "Is this service verified", please also change the options into radio buttons
![image](https://user-images.githubusercontent.com/65980846/122647890-2935ec80-d12f-11eb-8d04-68c3a81cac15.png)

- [x] Replace phase selection into adjustable bar
![image](https://user-images.githubusercontent.com/65980846/122647888-2509cf00-d12f-11eb-94a0-5772fe5ff55b.png)

**Comment by valto** [comment]
@alhasanmhdali & @abhijeets-ht in the accordion "next" is not needed, so we can skip that. 

Also the "publish" button is better to say "save" and it should be possible to save at any point. 

The logic of this form, is that, it's not meant to be filled "in one go" as most of those filling the information, don't have all information at hand. But at the same time any information made available, is better than not having anything listed about the service. 

Ie even if just having name of service with development phases + link to actual service website, is valuable.

Since @alhasanmhdali created those changes as "checklist" here, @abhijeets-ht please mark those that are done by checking the box here.

**Comment by valto** [comment]
Also one more change to design itself 

- [ ] The venue option can have multiple locations, so it should have possibility to '+add another venue'

**Comment by valto** [comment]
Also @MatiasNurmi & @alhasanmhdali - please make sure that all relevant details are also documented to PRD & Relevant user story google doc, so that these are not left only in places where information will eventually disappear after completed.

**Comment by abhijeets-ht** [comment]
Thanks @alhasanmhdali @valto for the above changes.
For , Remove "Application" section after service type --- How we can identify the service we are saved and after saving we can place on map in area "market (external)" and Organization (Internal)

**Comment by abhijeets-ht** [comment]
@alhasanmhdali I have made the above changes except for Drag & drop service template into map canvas. It's still in progress we are creating our own custom map to save services.

Please find the updated vercel link with the above changes suggested 
https://startup-commons-pm2l80d5c-abhijeetsht.vercel.app/

**Comment by abhijeets-ht** [comment]
@alhasanmhdali @valto 
I have made the above changes except for Drag & drop service template into map canvas. It's still in progress we are creating our own custom map to save services.

Please find the updated Vercel link with the above changes suggested
https://startup-commons-pm2l80d5c-abhijeetsht.vercel.app/
